wallets:
  - DEMO_WALLET
country: AU
tz: Australia/Melbourne
method: FIFO
price_source: auto
fx_source: frankfurter
airdrop_cost: zero
treat_liquidity_as_disposal: false
external_lot_tracking: true
apply_cgt_discount: false
api_keys:
  helius: YOUR_KEY
  birdeye: YOUR_KEY
  jupiter: YOUR_KEY
helius_enhanced_base_url: https://api-mainnet.helius-rpc.com
helius_rpc_url: null
helius_tx_limit: 100
helius_max_pages: 100
